epl/clubs/routes.py
from flask import Blueprint, render_template,redirect, url_for , request , flash
from epl.extension import db
from epl.models import Club

clubs_bp = Blueprint('clubs', __name__, template_folder='templates')

@clubs_bp.route('/')
def index():
  query = db.select(Club)
  clubs = db.session.scalars(query).all()
  return render_template('clubs/index.html',
                         title='Clubs Page',
                         clubs=clubs)

@clubs_bp.route('/new', methods=['GET', 'POST'])
def new_club():
  if request.method == 'POST':
    name = request.form['name']
    stadium = request.form['stadium']
    year = int(request.form['year'])
    logo = request.form['logo']

    club = Club(name=name, stadium=stadium, year=year, logo=logo)
    db.session.add(club)
    db.session.commit()

    flash('add new club successfully', 'success')
    return redirect(url_for('clubs.index'))
  
  return render_template('clubs/new_club.html',
                         title='New Club Page',
                         )

@clubs_bp.route('/search', methods=['GET', 'POST'])
def search_club():
  if request.method == 'POST':
    club_name = request.form['club_name']
    query = db.select(Club).where(Club.name.like(f'%{club_name}%'))
    clubs = db.session.scalars(query).all()

    return render_template('clubs/search_club.html',
                           title='Search Club Page',
                           clubs=clubs)
  
@clubs_bp.route('/<int:id>/info')
def info_club(id):
  club = db.session.get(Club, id)
  return render_template('clubs/info_club.html',
                         title='Info Club Page',
                         club=club)

@clubs_bp.route('/clubs/<int:id>/update', methods=['GET', 'POST'])
def update_club(id):
  club = db.session.get(Club, id)
  if request.method == 'POST':
    name = request.form['name']
    stadium = request.form['stadium']
    year = int(request.form['year'])
    logo = request.form['logo']

    club.name = name
    club.stadium = stadium
    club.year = year
    club.logo = logo

    db.session.add(club)
    db.session.commit()

    flash('update club successfully', 'success')
    return redirect(url_for('clubs.index'))
  
  return render_template('clubs/update_club.html',
                         title='Update Club Page',
                         club=club)

epl/clubs/templates/clubs/index.html
{% extends 'layout.html' %}

{% block title %}
  {{title}}
{% endblock %}

{% block content %}
  <div class="container mt-3">
    <h2>{{title}}</h2>
    <hr>
    <div class="row">
      <div class="col">
        <a href="{{url_for('clubs.new_club')}}" class="btn btn-outline-success">
          <i class="bi bi-folder-plus"></i>
          Add New Club
        </a>
      </div>
      <div class="col">
        <div class="input-group mb-3">
          <input name="club_name" type="text" class="form-control" placeholder="Search by Club's name"
            hx-target="#result"
            hx-post="{{url_for('clubs.search_club')}}"
            hx-trigger="keyup changed delay:200ms">
          <button class="btn btn-outline-secondary" type="button">
            <i class="bi bi-search"></i>
          </button>
        </div>
      </div>
    </div>
    <table class="table table-hover mt-3">
      <thead>
        <th>#</th>
        <th>Club Name</th>
        <th>Action</th>
      </thead>
      <tbody id="result">
        {% for club in clubs %}
          <tr>
            <td>{{loop.index}}</td>
            <td>{{club.name}}</td>
            <td>
              <a href="{{url_for('clubs.info_club', id=club.id)}}" class="btn btn-outline-info btn-sm">
                <i class="bi bi-info-circle"></i>
              </a>
            </td>
          </tr>
        {% endfor %}
        
      </tbody>
    </table>
  </div>
{% endblock %}

epl/clubs/templates/clubs/info_club.html
{% extends 'layout.html' %}

{% block title %}
  {{title}}
{% endblock %}

{% block content %}
  <div class="container mt-3">
    <h2>{{title}}</h2>
    <hr>
    <div class="row mb-3">
      <div class="col-md-4 mt-3">
        <div class="card">
          <img src="{{ club.logo }}" alt="" class="img-thumbnail p-5">
          <div>
            <h4 class="text-center text-success">
              Club Logo
            </h4>
          </div>
        </div>
      </div>
      <div class="col-md-8 mt-3">
        <div class="card">
          <div class="card-body">
            <div class="row">
              <div class="col"><h2>{{ club.name }}</h2></div>
              <div class="col"><h2 class="text-secondary float-end">club name</h2></div>
            </div>
            <hr>
            <div class="row">
              <div class="col"><h2>{{ club.stadium }}</h2></div>
              <div class="col"><h2 class="text-secondary float-end">stadium</h2></div>
            </div>
            <hr>
            <div class="row">
              <div class="col"><h2>{{ club.year }}</h2></div>
              <div class="col"><h2 class="text-secondary float-end">EST. year</h2></div>
            </div>
            <hr>
            <div class="row mt-5">
              <div class="col">
                <a href="{{ url_for('clubs.index') }}" class="btn btn-outline-success">
                  <i class="bi bi-house-up-fill"></i>
                  Back to Club Page
                </a>
              </div>
              <div class="col">
                <a href="{{ url_for('clubs.update_club', id=club.id) }}" class="float-end btn btn-outline-success">
                  <i class="bi bi-house-up-fill"></i>
                  Edit Club
                </a>
              </div>
            </div>
            <hr>
          </div>
        </div>
      </div>
    </div>
    
  </div>
{% endblock %}

epl/clubs/templates/clubs/new_club.html
{% extends 'layout.html' %}

{% block title %}
  {{title}}
{% endblock %}

{% block content %}
  <div class="container mt-3 mb-5">
    <h2>{{title}}</h2>
    <hr>
    <form method="post">
      <div class="mb-3">
        <label for="name" class="form-label">Club Name</label>
        <input name="name" type="text" class="form-control" id="name" required>
      </div>
      <div class="mb-3">
        <label for="stadium" class="form-label">Stadium Name</label>
        <input name="stadium" type="text" class="form-control" id="stadium" required>
      </div>
      <div class="mb-3">
        <label for="year" class="form-label">Year</label>
        <input name="year" type="number" class="form-control" id="year" required>
      </div>
      <div class="mb-3">
        <label for="logo" class="form-label">Logo URL</label>
        <input name="logo" type="text" class="form-control" id="logo" required>
      </div>
      <button type="submit" class="btn btn-outline-success">
        <i class="bi bi-folder-plus"></i>
        New Club
      </button>
    </form>
  </div>
{% endblock %}

epl/clubs/templates/clubs/search_club.html
{% for club in clubs %}
  <tr>
    <td>{{loop.index}}</td>
    <td>{{club.name}}</td>
    <td>
      <a href="{{ url_for('clubs.info_club', id=club.id) }}" class="btn btn-outline-info btn-sm">
        <i class="bi bi-info-circle"></i>
      </a>
    </td>
  </tr>
{% endfor %}

epl/clubs/templates/clubs/update_club.html
{% extends 'layout.html' %}

{% block title %}
  {{title}}
{% endblock %}

{% block content %}
  <div class="container mt-3 mb-5">
    <h2>{{title}}</h2>
    <hr>
    <form method="post">
      <div class="mb-3">
        <label for="name" class="form-label">Club Name</label>
        <input value="{{ club.name }}" name="name" type="text" class="form-control" id="name" required>
      </div>
      <div class="mb-3">
        <label for="stadium" class="form-label">Stadium Name</label>
        <input value="{{ club.stadium }}" name="stadium" type="text" class="form-control" id="stadium" required>
      </div>
      <div class="mb-3">
        <label for="year" class="form-label">Year</label>
        <input value="{{ club.year }}" name="year" type="number" class="form-control" id="year" required>
      </div>
      <div class="mb-3">
        <label for="logo" class="form-label">Logo URL</label>
        <input value="{{ club.logo }}" name="logo" type="text" class="form-control" id="logo" required>
      </div>
      <button type="submit" class="btn btn-outline-success">
        <i class="bi bi-pencil-square"></i>
        Update Club
      </button>
    </form>
  </div>
{% endblock %}