epl/players/routes.py
from flask import Blueprint, render_template, redirect, url_for, request, flash
from epl.extension import db
from epl.models import Club, Player

players_bp = Blueprint('players', __name__, template_folder='templates')

@players_bp.route('/')
def index():
  query = db.select(Player)
  players = db.session.scalars(query).all()
  return render_template('players/index.html',
                         title='Players Page',
                         players=players)

@players_bp.route('/new', methods=['GET', 'POST'])
def new_player():
  if request.method == 'POST':
    name = request.form['name']
    position = request.form['position']
    nationality = request.form['nationality']
    img = request.form['img']
    goal = int(request.form.get('goal', 0))
    squad_no = request.form.get('squad_no')
    clean_sheet = int(request.form.get('clean_sheet', 0)) if position == 'Goalkeeper' else 0
    club_id = int(request.form['club_id'])
    
    player = Player(name=name, position=position, nationality=nationality, 
                    img=img, goal=goal, squad_no=squad_no, clean_sheet=clean_sheet, club_id=club_id)
    db.session.add(player)
    db.session.commit()
    
    flash('add new player successfully', 'success')
    return redirect(url_for('players.index'))
  
  query = db.select(Club)
  clubs = db.session.scalars(query).all()
  return render_template('players/new_player.html',
                         title='New Player Page',
                         clubs=clubs)

@players_bp.route('/search', methods=['GET', 'POST'])
def search_player():
  if request.method == 'POST':
    player_name = request.form['player_name']
    query = db.select(Player).where(Player.name.like(f'%{player_name}%'))
    players = db.session.scalars(query).all()

    return render_template('players/search_player.html',
                           title='Search Player Page',
                           players=players)

@players_bp.route('/<int:id>/info')
def info_player(id):
  player = db.session.get(Player, id)
  return render_template('players/info_player.html',
                         title='Info Player Page',
                         player=player)

@players_bp.route('/<int:id>/update', methods=['GET', 'POST'])
def update_player(id):
  player = db.session.get(Player, id)
  if request.method == 'POST':
    name = request.form['name']
    position = request.form['position']
    nationality = request.form['nationality']
    img = request.form['img']
    goal = int(request.form.get('goal', 0))
    squad_no = request.form.get('squad_no')
    clean_sheet = int(request.form.get('clean_sheet', 0)) if position == 'Goalkeeper' else 0
    club_id = int(request.form['club_id'])

    player.name = name
    player.position = position
    player.nationality = nationality
    player.img = img
    player.goal = goal
    player.squad_no = squad_no
    player.clean_sheet = clean_sheet
    player.club_id = club_id

    db.session.add(player)
    db.session.commit()

    flash('update player successfully', 'success')
    return redirect(url_for('players.index'))
  
  query = db.select(Club)
  clubs = db.session.scalars(query).all()
  return render_template('players/update_player.html',
                         title='Update Player Page',
                         player=player,
                         clubs=clubs)

epl/players/templates/players/index.html
{% extends 'layout.html' %}

{% block title %}
  {{title}}
{% endblock %}

{% block content %}
  <div class="container mt-3">
    <h2>{{title}}</h2>
    <hr>
    <div class="row">
      <div class="col">
        <a href="{{url_for('players.new_player')}}" class="btn btn-outline-success">
          <i class="bi bi-folder-plus"></i>
          Add New Player
        </a>
      </div>
      <div class="col">
        <div class="input-group mb-3">
          <input name="player_name" type="text" class="form-control" placeholder="Search by Player's name"
            hx-target="#result"
            hx-post="{{url_for('players.search_player')}}"
            hx-trigger="keyup changed delay:200ms">
          <button class="btn btn-outline-secondary" type="button">
            <i class="bi bi-search"></i>
          </button>
      </div>
    </div>
    <table class="table table-hover mt-3">
      <thead>
        <th>#</th>
        <th>Player Name</th>
        <th>Action</th>
      </thead>
      <tbody id="result">
        {% for player in players %}
          <tr>
            <td>{{loop.index}}</td>
            <td>{{player.name}}</td>
            <td>
              <a href="{{ url_for('players.info_player', id=player.id) }}" class="btn btn-outline-info btn-sm">
                <i class="bi bi-info-circle"></i>
              </a>
            </td>
          </tr>
        {% endfor %}
        
      </tbody>
    </table>
  </div>
{% endblock %}

epl/players/templates/players/info_player.html
{% extends 'layout.html' %}

{% block title %}
  {{title}}
{% endblock %}

{% block content %}
  <div class="container mt-3 mb-3">
    <h2>{{title}}</h2>
    <hr>
    <div class="row mb-3">
      <div class="col-md-4 mt-3">
        <div class="card">
          <img src="{{ player.img }}" alt="{{ player.name }}" class="img-thumbnail p-5">
          <div>
            <h4 class="text-center text-success">
              Player Photo
            </h4>
          </div>
        </div>
      </div>
      <div class="col-md-8 mt-3">
        <div class="card">
          <div class="card-body">
            <div class="row">
              <div class="col"><h2>Player name</h2></div>
              <div class="col"><h2 class="text-secondary float-end">{{ player.name }}</h2></div>
            </div>
            <hr>
            <div class="row">
              <div class="col"><h2>Position</h2></div>
              <div class="col"><h2 class="text-secondary float-end">{{ player.position }}</h2></div>
            </div>
            <hr>
            <div class="row">
              <div class="col"><h2>Nationality</h2></div>
              <div class="col"><h2 class="text-secondary float-end">{{ player.nationality }}</h2></div>
            </div>
            <hr>
            <div class="row">
              <div class="col"><h2>Goals</h2></div>
              <div class="col"><h2 class="text-secondary float-end">{{ player.goal }}</h2></div>
            </div>
            <hr>
            <hr>
            <div class="row">
              <div class="col"><h2>Squad Number</h2></div>
              <div class="col"><h2 class="text-secondary float-end">{{ player.squad_no }}</h2></div>
            </div>
            <hr>
            {% if player.position == 'Goalkeeper' %}
            <div class="row">
              <div class="col"><h2>Clean Sheet</h2></div>
              <div class="col"><h2 class="text-secondary float-end">{{ player.clean_sheet }}</h2></div>
            </div>
            <hr>
            {% endif %}
            
            <div class="row mt-5">
              <div class="col">
                <a href="{{ url_for('players.index') }}" class="btn btn-outline-success">
                  <i class="bi bi-house-up-fill"></i>
                  Back to Player Page
                </a>
              </div>
              <div class="col">
                <a href="{{ url_for('players.update_player', id=player.id) }}" class="float-end btn btn-outline-success">
                  <i class="bi bi-house-up-fill"></i>
                  Edit Player
                </a>
              </div>
            </div>
            <hr>
          </div>
        </div>
      </div>
    </div>
    
  </div>
{% endblock %}

epl/players/templates/players/new_player.html
{% extends 'layout.html' %}

{% block title %}
  {{title}}
{% endblock %}

{% block content %}
  <div class="container mt-3 mb-3">
    <h2>{{title}}</h2>
    <hr>
    <form method="post">
      <div class="mb-3">
        <label for="name" class="form-label">Player Name</label>
        <input name="name" type="text" class="form-control" id="name" required>
      </div>
      <div class="mb-3">
        <label for="position" class="form-label">Select Position</label>
        <select name="position" class="form-select" aria-label="Default select example">
          <option value="Goalkeeper">Goalkeeper</option>
          <option value="Defender">Defender</option>
          <option value="Midfielder">Midfielder</option>
          <option value="Forward">Forward</option>
        </select>
      </div>
      <div class="mb-3">
        <label for="nationality" class="form-label">Nationality</label>
        <input name="nationality" type="text" class="form-control" id="nationality" required>
      </div>
      <div class="mb-3">
        <label for="goals" class="form-label">Goals</label>
        <input name="goal" type="number" class="form-control" id="goals" value="0">
      </div>
      <div class="mb-3">
        <label for="clean_sheet" class="form-label">Clean Sheet </label>
        <input name="clean_sheet" type="number" class="form-control" id="clean_sheet" value="0" min="0">
      </div>
      <div class="mb-3">
        <label for="squad_no" class="form-label">Squad Number</label>
        <input name="squad_no" type="number" class="form-control" id="squad_no">
      </div>
      <div class="mb-3">
        <label for="img" class="form-label">Image URL</label>
        <input name="img" type="text" class="form-control" id="img" required>
      </div>
      <div class="mb-3">
        <label for="club_id" class="form-label">Select Club</label>
        <select name="club_id" class="form-select" aria-label="Default select example" required>
          <option value="">-- Select Club --</option>
          {% for club in clubs %}
            <option value="{{ club.id }}">{{ club.name }}</option>
          {% endfor %}
        </select>
      </div>
      <button type="submit" class="btn btn-outline-success">
        <i class="bi bi-folder-plus"></i>
        New Player
      </button>
    </form>
  </div>
{% endblock %}

epl/players/templates/players/search_player.html
{% for player in players %}
  <tr>
    <td>{{ loop.index }}</td>
    <td>{{ player.name }}</td>
    <td>
      <a href="{{ url_for('players.info_player', id=player.id) }}" class="btn btn-outline-info btn-sm">
        <i class="bi bi-info-circle"></i>
      </a>
    </td>
  </tr>
{% endfor %}

epl/players/templates/players/update_player.html
{% extends 'layout.html' %}

{% block title %}
  {{title}}
{% endblock %}

{% block content %}
  <div class="container mt-3">
    <h2>{{title}}</h2>
    <hr>
    <form method="post">
      <div class="mb-3">
        <label for="name" class="form-label">Player Name</label>
        <input value="{{player.name}}" name="name" type="text" class="form-control" id="name" required>
      </div>
      <div class="mb-3">
        <label for="position" class="form-label">Select Position</label>
        <select name="position" class="form-select" aria-readonly="true">
          <option value="Goalkeeper" {% if player.position == 'Goalkeeper' %}
            selected
          {% endif %}
          >Goalkeeper</option>
          <option value="Defender" {% if player.position == 'Defender' %}
            selected
          {% endif %}>Defender</option>
          <option value="Midfielder" {% if player.position == 'Midfielder' %}
            selected
          {% endif %}>Midfielder</option>
          <option value="Forward" {% if player.position == 'Forward' %}
            selected
          {% endif %}>Forward</option>
        </select>
      </div>
      <div class="mb-3">
        <label for="nationality" class="form-label">Nationality</label>
        <input value="{{player.nationality}}" name="nationality" type="text" class="form-control" id="nationality" required>
      </div>
      <div class="mb-3">
        <label for="goal" class="form-label">Goals</label>
        <input value="{{player.goal}}" name="goal" type="number" class="form-control" id="goal" required>
      </div>
      <div class="mb-3">
        <label for="clean_sheet" class="form-label">Clean Sheet </label>
        <input value="{{player.clean_sheet}}" name="clean_sheet" type="number" class="form-control" id="clean_sheet" min="0" required>
      </div>
      <div class="mb-3">
        <label for="squad_no" class="form-label">Squad No</label>
        <input value="{{player.squad_no}}" name="squad_no" type="number" class="form-control" id="squad_no" required>
      </div>
      <div class="mb-3">
        <label for="img" class="form-label">Image URL</label>
        <input value="{{player.img}}" name="img" type="text" class="form-control" id="img" required>
      </div>
      <div class="mb-3">
        <label for="position" class="form-label">Select Club</label>
        <select name="club_id" class="form-select" aria-label="Default select example">
          {% for club in clubs %}
            <option value="{{club.id}}" {% if player.club.name == club.name %}
              selected
            {% endif %}
            >{{club.name}}</option>
          {% endfor %}
          
        </select>
      </div>
      <button type="submit" class="btn btn-outline-success">
        <i class="bi bi-pencil-square"></i>
        Update Club
      </button>
    </form>
  </div>
{% endblock %}