epl/models.py
from epl import db
from sqlalchemy import Column, Integer, String, ForeignKey
from sqlalchemy.orm import relationship , Mapped , mapped_column
from typing import List

class Club(db.Model):
    __tablename__ = 'club'
    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    name: Mapped[str] = mapped_column(String(50), nullable=False , unique=True)
    stadium: Mapped[str] = mapped_column(String(100), nullable=False)
    year: Mapped[int] = mapped_column(Integer, nullable=False)
    logo: Mapped[str] = mapped_column(String(256), nullable=False)

    players: Mapped[List['Player']] = relationship(back_populates="club")

    def __repr__(self) -> str:
        return f"Clubs({self.name})"

    
class Player(db.Model):
    __tablename__ = 'player'
    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    name: Mapped[str] = mapped_column(String(50), nullable=False , unique=True)
    position: Mapped[str] = mapped_column(String(20), nullable=False)
    nationality: Mapped[str] = mapped_column(String(25), nullable=False)
    goal: Mapped[int] = mapped_column(Integer, nullable=True, default=0)
    squad_no: Mapped[int] = mapped_column(Integer, nullable=True)
    img: Mapped[str] = mapped_column(String(256), nullable=False)
    clean_sheet: Mapped[int] = mapped_column(Integer, nullable=True, default=0)
    club_id: Mapped[int] = mapped_column(Integer, ForeignKey('club.id'))

    club: Mapped['Club'] = relationship(back_populates='players')
    def __repr__(self):
        return f"<Players {self.name}>"

epl/__init__.py
from flask import Flask
from epl.extension import db, migrate
from epl.core.routes import core_bp
from epl.clubs.routes import clubs_bp
from epl.players.routes import players_bp
# from epl.models import Club, Player

def create_app():
    app = Flask(__name__)
    app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///epl.db'
    app.secret_key = b'asjdlkdjlkasdjlkasjdlkjasdjasdlk'

    db.init_app(app)
    migrate.init_app(app, db)
    app.register_blueprint(core_bp, url_prefix='/')
    app.register_blueprint(clubs_bp, url_prefix='/clubs')
    app.register_blueprint(players_bp, url_prefix='/players')


    return app

epl/clubs/routes.py
from flask import Blueprint, render_template,redirect, url_for , request , flash
from epl.extension import db
from epl.models import Club

clubs_bp = Blueprint('clubs', __name__, template_folder='templates')

@clubs_bp.route('/')
def index():
  query = db.select(Club)
  clubs = db.session.scalars(query).all()
  return render_template('clubs/index.html',
                         title='Clubs Page',
                         clubs=clubs)

@clubs_bp.route('/new', methods=['GET', 'POST'])
def new_club():
  if request.method == 'POST':
    name = request.form['name']
    stadium = request.form['stadium']
    year = int(request.form['year'])
    logo = request.form['logo']

    club = Club(name=name, stadium=stadium, year=year, logo=logo)
    db.session.add(club)
    db.session.commit()

    flash('add new club successfully', 'success')
    return redirect(url_for('clubs.index'))
  
  return render_template('clubs/new_club.html',
                         title='New Club Page',
                         )

@clubs_bp.route('/search', methods=['GET', 'POST'])
def search_club():
  if request.method == 'POST':
    club_name = request.form['club_name']
    query = db.select(Club).where(Club.name.like(f'%{club_name}%'))
    clubs = db.session.scalars(query).all()

    return render_template('clubs/search_club.html',
                           title='Search Club Page',
                           clubs=clubs)
  
@clubs_bp.route('/<int:id>/info')
def info_club(id):
  club = db.session.get(Club, id)
  return render_template('clubs/info_club.html',
                         title='Info Club Page',
                         club=club)

@clubs_bp.route('/clubs/<int:id>/update', methods=['GET', 'POST'])
def update_club(id):
  club = db.session.get(Club, id)
  if request.method == 'POST':
    name = request.form['name']
    stadium = request.form['stadium']
    year = int(request.form['year'])
    logo = request.form['logo']

    club.name = name
    club.stadium = stadium
    club.year = year
    club.logo = logo

    db.session.add(club)
    db.session.commit()

    flash('update club successfully', 'success')
    return redirect(url_for('clubs.index'))
  
  return render_template('clubs/update_club.html',
                         title='Update Club Page',
                         club=club)

epl/core/routes.py
from flask import Blueprint, render_template

core_bp = Blueprint('core', __name__ , template_folder='templates')

@core_bp.route('/')
def index():
    return render_template('core/index.html', title='Home Page')

epl/players/routes.py
from flask import Blueprint, render_template, redirect, url_for, request, flash
from epl.extension import db
from epl.models import Club, Player

players_bp = Blueprint('players', __name__, template_folder='templates')

@players_bp.route('/')
def index():
  query = db.select(Player)
  players = db.session.scalars(query).all()
  return render_template('players/index.html',
                         title='Players Page',
                         players=players)

@players_bp.route('/new', methods=['GET', 'POST'])
def new_player():
  if request.method == 'POST':
    name = request.form['name']
    position = request.form['position']
    nationality = request.form['nationality']
    img = request.form['img']
    goal = int(request.form.get('goal', 0))
    squad_no = request.form.get('squad_no')
    clean_sheet = int(request.form.get('clean_sheet', 0)) if position == 'Goalkeeper' else 0
    club_id = int(request.form['club_id'])
    
    player = Player(name=name, position=position, nationality=nationality, 
                    img=img, goal=goal, squad_no=squad_no, clean_sheet=clean_sheet, club_id=club_id)
    db.session.add(player)
    db.session.commit()
    
    flash('add new player successfully', 'success')
    return redirect(url_for('players.index'))
  
  query = db.select(Club)
  clubs = db.session.scalars(query).all()
  return render_template('players/new_player.html',
                         title='New Player Page',
                         clubs=clubs)

@players_bp.route('/search', methods=['GET', 'POST'])
def search_player():
  if request.method == 'POST':
    player_name = request.form['player_name']
    query = db.select(Player).where(Player.name.like(f'%{player_name}%'))
    players = db.session.scalars(query).all()

    return render_template('players/search_player.html',
                           title='Search Player Page',
                           players=players)

@players_bp.route('/<int:id>/info')
def info_player(id):
  player = db.session.get(Player, id)
  return render_template('players/info_player.html',
                         title='Info Player Page',
                         player=player)

@players_bp.route('/<int:id>/update', methods=['GET', 'POST'])
def update_player(id):
  player = db.session.get(Player, id)
  if request.method == 'POST':
    name = request.form['name']
    position = request.form['position']
    nationality = request.form['nationality']
    img = request.form['img']
    goal = int(request.form.get('goal', 0))
    squad_no = request.form.get('squad_no')
    clean_sheet = int(request.form.get('clean_sheet', 0)) if position == 'Goalkeeper' else 0
    club_id = int(request.form['club_id'])

    player.name = name
    player.position = position
    player.nationality = nationality
    player.img = img
    player.goal = goal
    player.squad_no = squad_no
    player.clean_sheet = clean_sheet
    player.club_id = club_id

    db.session.add(player)
    db.session.commit()

    flash('update player successfully', 'success')
    return redirect(url_for('players.index'))
  
  query = db.select(Club)
  clubs = db.session.scalars(query).all()
  return render_template('players/update_player.html',
                         title='Update Player Page',
                         player=player,
                         clubs=clubs)

epl/templates/clubs/index.html
{% extends 'layout.html' %}

{% block title %}
  {{title}}
{% endblock %}

{% block content %}
  <div class="container mt-3">
    <h2>{{title}}</h2>
    <hr>
    <div class="row">
      <div class="col">
        <a href="{{url_for('new_club')}}" class="btn btn-outline-success">
          <i class="bi bi-folder-plus"></i>
          Add New Club
        </a>
      </div>
      <div class="col">
        <!-- <form method="post"
        hx-target="#result"
        hx-post="{{url_for('search_club')}}"
        hx-trigger="submit"
        hx-on::after-request="if(event.detail.successful) this.reset()">
          <div class="input-group mb-3">
            <input name="club_name" type="text" class="form-control" placeholder="Search by Club's name">
            <button class="btn btn-outline-secondary" type="submit">
              <i class="bi bi-search"></i>
            </button>
          </div>
        </form> -->
        <div class="input-group mb-3">
          <input name="club_name" type="text" class="form-control" placeholder="Search by Club's name"
            hx-target="#result"
            hx-post="{{url_for('search_club')}}"
            hx-trigger="keyup changed delay:200ms">
          <button class="btn btn-outline-secondary" type="button">
            <i class="bi bi-search"></i>
          </button>
        </div>
      </div>
    </div>
    <table class="table table-hover mt-3">
      <thead>
        <th>#</th>
        <th>Club Name</th>
        <th>Action</th>
      </thead>
      <tbody id="result">
        {% for club in clubs %}
          <tr>
            <td>{{loop.index}}</td>
            <td>{{club.name}}</td>
            <td>
              <a href="{{url_for('info_club', id=club.id)}}" class="btn btn-outline-info btn-sm">
                <i class="bi bi-info-circle"></i>
              </a>
            </td>
          </tr>
        {% endfor %}
        
      </tbody>
    </table>
  </div>
{% endblock %}

epl/templates/clubs/info_club.html
{% extends 'layout.html' %}

{% block title %}
  {{title}}
{% endblock %}

{% block content %}
  <div class="container mt-3">
    <h2>{{title}}</h2>
    <hr>
    <div class="row mb-3">
      <div class="col-md-4 mt-3">
        <div class="card">
          <img src="{{ club.logo }}" alt="" class="img-thumbnail p-5">
          <div>
            <h4 class="text-center text-success">
              Club Logo
            </h4>
          </div>
        </div>
      </div>
      <div class="col-md-8 mt-3">
        <div class="card">
          <div class="card-body">
            <div class="row">
              <div class="col"><h2>{{ club.name }}</h2></div>
              <div class="col"><h2 class="text-secondary float-end">club name</h2></div>
            </div>
            <hr>
            <div class="row">
              <div class="col"><h2>{{ club.stadium }}</h2></div>
              <div class="col"><h2 class="text-secondary float-end">stadium</h2></div>
            </div>
            <hr>
            <div class="row">
              <div class="col"><h2>{{ club.year }}</h2></div>
              <div class="col"><h2 class="text-secondary float-end">EST. year</h2></div>
            </div>
            <hr>
            <div class="row mt-5">
              <div class="col">
                <a href="{{ url_for('all_clubs') }}" class="btn btn-outline-success">
                  <i class="bi bi-house-up-fill"></i>
                  Back to Club Page
                </a>
              </div>
              <div class="col">
                <a href="{{ url_for('update_club', id=club.id) }}" class="float-end btn btn-outline-success">
                  <i class="bi bi-house-up-fill"></i>
                  Edit Club
                </a>
              </div>
            </div>
            <hr>
          </div>
        </div>
      </div>
    </div>
    
  </div>
{% endblock %}

epl/templates/clubs/search_club.html
{% for club in clubs %}
  <tr>
    <td>{{loop.index}}</td>
    <td>{{club.name}}</td>
    <td>
      <a href="{{ url_for('info_club', id=club.id) }}" class="btn btn-outline-info btn-sm">
        <i class="bi bi-info-circle"></i>
      </a>
    </td>
  </tr>
{% endfor %}

epl/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.13.1/font/bootstrap-icons.min.css">
  <link href="https://fonts.googleapis.com/css2?family=Nunito:ital,wght@0,200..1000;1,200..1000&display=swap" rel="stylesheet">
  <title>EPL BP - {% block title %}{% endblock %}
  </title>
  <style>
    * {
      font-family: 'Nunito', sans-serif;
    }
  </style>
  <script src="https://cdn.jsdelivr.net/npm/htmx.org@2.0.8/dist/htmx.min.js" integrity="sha384-/TgkGk7p307TH7EXJDuUlgG3Ce1UVolAOFopFekQkkXihi5u/6OCvVKyz1W+idaz" crossorigin="anonymous"></script>
</head>
<body>
  {% include "navbar.html" %}
  {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
      
      {% for category, message in messages %}
        <div class="alert alert-{{category}} alert-dismissible fade show" role="alert">
          <strong>{{message}}</strong>
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
      {% endfor %}
      
    {% endif %}
  {% endwith %}
  {% block content %}{% endblock %}
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/js/bootstrap.bundle.min.js" integrity="sha384-FKyoEForCGlyvwx9Hj09JcYn3nv7wiPVlz7YYwJrWVcXK/BmnVDxM+D2scQbITxI" crossorigin="anonymous"></script>
</body>
</html>

epl/templates/navbar.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="{{url_for('core.index')}}">EPL</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{{url_for('core.index')}}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{url_for('clubs.index')}}">Clubs</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{url_for('players.index')}}">Players</a>
        </li>
       
      </ul>
    </div>
  </div>
</nav>

epl/templates/players/index.html
{% extends 'layout.html' %}

{% block title %}
  {{title}}
{% endblock %}

{% block content %}
  <div class="container mt-3">
    <h2>{{title}}</h2>
    <hr>
    <div class="row">
      <div class="col">
        <a href="{{url_for('new_player')}}" class="btn btn-outline-success">
          <i class="bi bi-folder-plus"></i>
          Add New Player
        </a>
      </div>
      <div class="col">
        <!-- <form method="post"
        hx-target="#result"
        hx-trigger="submit"
        hx-post="{{url_for('search_player')}}"
        hx-on::after-request="if(event.detail.successful) this.reset()">
          <div class="input-group mb-3">
            <input name="player_name" type="text" class="form-control" placeholder="Search by Player's name">
            <button class="btn btn-outline-secondary" type="submit">
              <i class="bi bi-search"></i>
            </button>
          </div>
        </form> -->
        <div class="input-group mb-3">
          <input name="player_name" type="text" class="form-control" placeholder="Search by Player's name"
            hx-target="#result"
            hx-post="{{url_for('search_player')}}"
            hx-trigger="keyup changed delay:200ms">
          <button class="btn btn-outline-secondary" type="button">
            <i class="bi bi-search"></i>
          </button>
      </div>
    </div>
    <table class="table table-hover mt-3">
      <thead>
        <th>#</th>
        <th>Player Name</th>
        <th>Action</th>
      </thead>
      <tbody id="result">
        {% for player in players %}
          <tr>
            <td>{{loop.index}}</td>
            <td>{{player.name}}</td>
            <td>
              <a href="{{ url_for('info_player', id=player.id) }}" class="btn btn-outline-info btn-sm">
                <i class="bi bi-info-circle"></i>
              </a>
            </td>
          </tr>
        {% endfor %}
        
      </tbody>
    </table>
  </div>
{% endblock %}

epl/templates/players/info_player.html
{% extends 'layout.html' %}

{% block title %}
  {{title}}
{% endblock %}

{% block content %}
  <div class="container mt-3 mb-3">
    <h2>{{title}}</h2>
    <hr>
    <div class="row mb-3">
      <div class="col-md-4 mt-3">
        <div class="card">
          <img src="{{ player.img }}" alt="{{ player.name }}" class="img-thumbnail p-5">
          <div>
            <h4 class="text-center text-success">
              Player Photo
            </h4>
          </div>
        </div>
      </div>
      <div class="col-md-8 mt-3">
        <div class="card">
          <div class="card-body">
            <div class="row">
              <div class="col"><h2>Player name</h2></div>
              <div class="col"><h2 class="text-secondary float-end">{{ player.name }}</h2></div>
            </div>
            <hr>
            <div class="row">
              <div class="col"><h2>Position</h2></div>
              <div class="col"><h2 class="text-secondary float-end">{{ player.position }}</h2></div>
            </div>
            <hr>
            <div class="row">
              <div class="col"><h2>Nationality</h2></div>
              <div class="col"><h2 class="text-secondary float-end">{{ player.nationality }}</h2></div>
            </div>
            <hr>
            <div class="row">
              <div class="col"><h2>Goals</h2></div>
              <div class="col"><h2 class="text-secondary float-end">{{ player.goal }}</h2></div>
            </div>
            <hr>
            
            <div class="row mt-5">
              <div class="col">
                <a href="{{ url_for('all_players') }}" class="btn btn-outline-success">
                  <i class="bi bi-house-up-fill"></i>
                  Back to Player Page
                </a>
              </div>
              <div class="col">
                <a href="{{ url_for('update_player', id=player.id) }}" class="float-end btn btn-outline-success">
                  <i class="bi bi-house-up-fill"></i>
                  Edit Player
                </a>
              </div>
            </div>
            <hr>
          </div>
        </div>
      </div>
    </div>
    
  </div>
{% endblock %}

epl/templates/players/search_player.html
{% for player in players %}
  <tr>
    <td>{{ loop.index }}</td>
    <td>{{ player.name }}</td>
    <td>
      <a href="{{ url_for('info_player', id=player.id) }}" class="btn btn-outline-info btn-sm">
        <i class="bi bi-info-circle"></i>
      </a>
    </td>
  </tr>
{% endfor %}

epl/templates/players/update_player.html
{% extends 'layout.html' %}

{% block title %}
  {{title}}
{% endblock %}

{% block content %}
  <div class="container mt-3">
    <h2>{{title}}</h2>
    <hr>
    <form method="post">
      <div class="mb-3">
        <label for="name" class="form-label">Player Name</label>
        <input value="{{player.name}}" name="name" readonly type="text" class="form-control" id="name" required>
      </div>
      <div class="mb-3">
        <label for="position" class="form-label">Select Position</label>
        <select name="position" class="form-select" aria-readonly="true">
          <option value="Goalkeeper" {% if player.position == 'Goalkeeper' %}
            selected
          {% endif %}
          >Goalkeeper</option>
          <option value="Defender" {% if player.position == 'Defender' %}
            selected
          {% endif %}>Defender</option>
          <option value="Midfielder" {% if player.position == 'Midfielder' %}
            selected
          {% endif %}>Midfielder</option>
          <option value="Forward" {% if player.position == 'Forward' %}
            selected
          {% endif %}>Forward</option>
        </select>
      </div>
      <div class="mb-3">
        <label for="nationality" class="form-label">Nationality</label>
        <input value="{{player.nationality}}" readonly name="nationality" type="text" class="form-control" id="nationality" required>
      </div>
      <div class="mb-3">
        <label for="goals" class="form-label">Goals</label>
        <input value="{{player.goals}}" name="goals" type="number" class="form-control" id="goals" required>
      </div>
      <div class="mb-3">
        <label for="squad_no" class="form-label">Squad No</label>
        <input value="{{player.squad_no}}" name="squad_no" type="number" class="form-control" id="squad_no" required>
      </div>
      <div class="mb-3">
        <label for="img" class="form-label">Image URL</label>
        <input value="{{player.img}}" name="img" type="text" class="form-control" id="img" required>
      </div>
      <div class="mb-3">
        <label for="position" class="form-label">Select Club</label>
        <select name="club_id" class="form-select" aria-label="Default select example">
          {% for club in clubs %}
            <option value="{{club.id}}" {% if player.club.name == club.name %}
              selected
            {% endif %}
            >{{club.name}}</option>
          {% endfor %}
          
        </select>
      </div>
      <button type="submit" class="btn btn-outline-success">
        <i class="bi bi-pencil-square"></i>
        Update Club
      </button>
    </form>
  </div>
{% endblock %}